style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/newrelic/terraform-newrelic-apm
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject